### ISSUE TITLE
Face and Eye Detection using open-cv

### ISSUE THREAD

**Issue by anubhav201241** [CodeTrophs/AI-Interview-Test#7]
Hi, I am Gssoc Participant. I would like to contribute,
I want to contribute the face, eye, and mid detection part which will detect the face, eyes, and nose part in the face with the use of python and open-cv. 

@aryasoni98  Please assign this part to me I would like to work upon it :) 

Thank You :))

**Comment by aryasoni98** [comment]
@anubhav201241 Go Head

**Comment by anubhav201241** [comment]
Thank you sir
